-- Plant-Ride initial schema.
-- Foreign keys are plain ids (no ORM relationships) to keep modules decoupled.
-- Every business table carries plant_id: one deployment can serve one or many plants.

CREATE TABLE system_setting (
    setting_key   VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(500) NOT NULL
);

CREATE TABLE plant (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                            VARCHAR(30)  NOT NULL UNIQUE,
    name                            VARCHAR(200) NOT NULL,
    timezone                        VARCHAR(60)  NOT NULL DEFAULT 'Asia/Kolkata',
    center_lat                      DOUBLE PRECISION,
    center_lng                      DOUBLE PRECISION,
    speed_limit_kmh                 INT          NOT NULL DEFAULT 30,
    dispatch_radius_km              DOUBLE PRECISION NOT NULL DEFAULT 10,
    offer_timeout_seconds           INT          NOT NULL DEFAULT 45,
    search_timeout_minutes          INT          NOT NULL DEFAULT 15,
    scheduled_dispatch_lead_minutes INT          NOT NULL DEFAULT 15,
    exclusive_ride_requires_approval BOOLEAN     NOT NULL DEFAULT TRUE,
    visitor_module_enabled          BOOLEAN      NOT NULL DEFAULT FALSE,
    active                          BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE department (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT       NOT NULL REFERENCES plant (id),
    code     VARCHAR(30)  NOT NULL,
    name     VARCHAR(200) NOT NULL,
    lat      DOUBLE PRECISION,
    lng      DOUBLE PRECISION,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_department_code UNIQUE (plant_id, code)
);

CREATE TABLE cost_center (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT        NOT NULL REFERENCES plant (id),
    code           VARCHAR(30)   NOT NULL,
    name           VARCHAR(200)  NOT NULL,
    department_id  BIGINT REFERENCES department (id),
    monthly_budget NUMERIC(14, 2),
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_cost_center_code UNIQUE (plant_id, code)
);

CREATE TABLE project (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT       NOT NULL REFERENCES plant (id),
    code           VARCHAR(40)  NOT NULL,
    name           VARCHAR(200) NOT NULL,
    cost_center_id BIGINT       NOT NULL REFERENCES cost_center (id),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_project_code UNIQUE (plant_id, code)
);

CREATE TABLE vendor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id     BIGINT       NOT NULL REFERENCES plant (id),
    name         VARCHAR(200) NOT NULL,
    contact_name VARCHAR(200),
    phone        VARCHAR(30),
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE app_user (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id               BIGINT       NOT NULL REFERENCES plant (id),
    login_id               VARCHAR(60)  NOT NULL UNIQUE,
    name                   VARCHAR(200) NOT NULL,
    phone                  VARCHAR(30),
    email                  VARCHAR(200),
    password_hash          VARCHAR(200) NOT NULL,
    role                   VARCHAR(20)  NOT NULL,
    grade                  VARCHAR(20),
    department_id          BIGINT REFERENCES department (id),
    default_cost_center_id BIGINT REFERENCES cost_center (id),
    manager_id             BIGINT REFERENCES app_user (id),
    vendor_id              BIGINT REFERENCES vendor (id),
    active                 BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE stop (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT           NOT NULL REFERENCES plant (id),
    code     VARCHAR(30)      NOT NULL,
    name     VARCHAR(200)     NOT NULL,
    lat      DOUBLE PRECISION NOT NULL,
    lng      DOUBLE PRECISION NOT NULL,
    active   BOOLEAN          NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_stop_code UNIQUE (plant_id, code)
);

-- Fixed-route service with metro-style headway: a departure from the first stop every
-- headway_minutes between first_departure and last_departure on the listed days.
CREATE TABLE route (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT       NOT NULL REFERENCES plant (id),
    code            VARCHAR(30)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    route_kind      VARCHAR(20)  NOT NULL,
    first_departure TIME         NOT NULL,
    last_departure  TIME         NOT NULL,
    headway_minutes INT          NOT NULL,
    days_of_week    VARCHAR(20)  NOT NULL DEFAULT '1,2,3,4,5,6,7',
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_route_code UNIQUE (plant_id, code)
);

CREATE TABLE route_stop (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id       BIGINT NOT NULL REFERENCES route (id) ON DELETE CASCADE,
    seq            INT    NOT NULL,
    stop_id        BIGINT NOT NULL REFERENCES stop (id),
    offset_minutes INT    NOT NULL,
    CONSTRAINT uq_route_stop_seq UNIQUE (route_id, seq)
);

CREATE TABLE vehicle (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id            BIGINT      NOT NULL REFERENCES plant (id),
    registration_no     VARCHAR(30) NOT NULL UNIQUE,
    vehicle_type        VARCHAR(20) NOT NULL,
    capacity            INT         NOT NULL,
    owner_type          VARCHAR(20) NOT NULL,
    owner_department_id BIGINT REFERENCES department (id),
    vendor_id           BIGINT REFERENCES vendor (id),
    service_mode        VARCHAR(20) NOT NULL,
    route_id            BIGINT REFERENCES route (id),
    gps_device_id       VARCHAR(60) UNIQUE,
    status              VARCHAR(20) NOT NULL DEFAULT 'OFF_DUTY',
    current_driver_id   BIGINT REFERENCES app_user (id),
    last_lat            DOUBLE PRECISION,
    last_lng            DOUBLE PRECISION,
    last_speed_kmh      DOUBLE PRECISION,
    last_fix_at         TIMESTAMP WITH TIME ZONE,
    active              BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE rate_card (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id     BIGINT         NOT NULL REFERENCES plant (id),
    vehicle_type VARCHAR(20)    NOT NULL,
    ride_type    VARCHAR(20)    NOT NULL,
    base_fare    NUMERIC(10, 2) NOT NULL,
    per_km       NUMERIC(10, 2) NOT NULL,
    per_minute   NUMERIC(10, 2) NOT NULL,
    minimum_fare NUMERIC(10, 2) NOT NULL,
    CONSTRAINT uq_rate_card UNIQUE (plant_id, vehicle_type, ride_type)
);

CREATE TABLE vehicle_position (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT                   NOT NULL REFERENCES vehicle (id),
    lat        DOUBLE PRECISION         NOT NULL,
    lng        DOUBLE PRECISION         NOT NULL,
    speed_kmh  DOUBLE PRECISION,
    fix_time   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_vehicle_position_vehicle_time ON vehicle_position (vehicle_id, fix_time);

CREATE TABLE safety_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id     BIGINT                   NOT NULL REFERENCES plant (id),
    vehicle_id   BIGINT                   NOT NULL REFERENCES vehicle (id),
    event_type   VARCHAR(30)              NOT NULL,
    lat          DOUBLE PRECISION,
    lng          DOUBLE PRECISION,
    speed_kmh    DOUBLE PRECISION,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_safety_event_plant_time ON safety_event (plant_id, occurred_at);

CREATE TABLE ride_request (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id            BIGINT           NOT NULL REFERENCES plant (id),
    requester_id        BIGINT           NOT NULL REFERENCES app_user (id),
    ride_type           VARCHAR(20)      NOT NULL,
    vehicle_type        VARCHAR(20),
    pickup_label        VARCHAR(200)     NOT NULL,
    pickup_lat          DOUBLE PRECISION NOT NULL,
    pickup_lng          DOUBLE PRECISION NOT NULL,
    drop_label          VARCHAR(200)     NOT NULL,
    drop_lat            DOUBLE PRECISION NOT NULL,
    drop_lng            DOUBLE PRECISION NOT NULL,
    scheduled_at        TIMESTAMP WITH TIME ZONE,
    passenger_count     INT              NOT NULL DEFAULT 1,
    purpose             VARCHAR(300),
    cost_center_id      BIGINT           NOT NULL REFERENCES cost_center (id),
    project_id          BIGINT REFERENCES project (id),
    visitor_name        VARCHAR(200),
    visitor_phone       VARCHAR(30),
    gate_pass_ref       VARCHAR(60),
    status              VARCHAR(30)      NOT NULL,
    approver_id         BIGINT REFERENCES app_user (id),
    vehicle_id          BIGINT REFERENCES vehicle (id),
    driver_id           BIGINT REFERENCES app_user (id),
    otp                 VARCHAR(6)       NOT NULL,
    rejected_driver_ids VARCHAR(1000),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    search_started_at   TIMESTAMP WITH TIME ZONE,
    offer_expires_at    TIMESTAMP WITH TIME ZONE,
    approved_at         TIMESTAMP WITH TIME ZONE,
    accepted_at         TIMESTAMP WITH TIME ZONE,
    arrived_at          TIMESTAMP WITH TIME ZONE,
    started_at          TIMESTAMP WITH TIME ZONE,
    completed_at        TIMESTAMP WITH TIME ZONE,
    cancelled_at        TIMESTAMP WITH TIME ZONE,
    cancel_reason       VARCHAR(300),
    distance_km         NUMERIC(10, 2),
    duration_minutes    INT,
    distance_source     VARCHAR(20),
    fare                NUMERIC(12, 2),
    version             BIGINT           NOT NULL DEFAULT 0
);
CREATE INDEX ix_ride_request_status ON ride_request (plant_id, status);
CREATE INDEX ix_ride_request_requester ON ride_request (requester_id, created_at);
CREATE INDEX ix_ride_request_driver ON ride_request (driver_id, status);

CREATE TABLE cost_allocation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id        BIGINT                   NOT NULL REFERENCES plant (id),
    ride_request_id BIGINT                   NOT NULL REFERENCES ride_request (id),
    cost_center_id  BIGINT                   NOT NULL REFERENCES cost_center (id),
    project_id      BIGINT REFERENCES project (id),
    amount          NUMERIC(12, 2)           NOT NULL,
    basis           VARCHAR(30)              NOT NULL,
    allocated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_cost_allocation_ride UNIQUE (ride_request_id, cost_center_id)
);
CREATE INDEX ix_cost_allocation_plant_time ON cost_allocation (plant_id, allocated_at);
