-- Push notification device registrations (one row per app install).
CREATE TABLE device_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES app_user (id),
    platform     VARCHAR(20)              NOT NULL,
    app          VARCHAR(20)              NOT NULL,
    token        VARCHAR(512)             NOT NULL UNIQUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_device_token_user ON device_token (user_id);

-- Configurable cost policies (Finance has not decided yet; defaults keep current behaviour).
ALTER TABLE plant ADD COLUMN department_vehicle_sharing VARCHAR(30) NOT NULL DEFAULT 'OWN_DEPARTMENT_ONLY';
ALTER TABLE plant ADD COLUMN own_vehicle_charge_mode VARCHAR(30) NOT NULL DEFAULT 'CHARGE';
ALTER TABLE plant ADD COLUMN lent_vehicle_charge_mode VARCHAR(30) NOT NULL DEFAULT 'CHARGE_BOOKER_CREDIT_OWNER';
ALTER TABLE plant ADD COLUMN shuttle_cost_allocation VARCHAR(30) NOT NULL DEFAULT 'NOT_ALLOCATED';
ALTER TABLE plant ADD COLUMN shuttle_central_cost_center_id BIGINT REFERENCES cost_center (id);

-- Fixed monthly cost of running a route (contract hire, fuel, driver), allocated per policy.
ALTER TABLE route ADD COLUMN monthly_cost NUMERIC(14, 2);

-- Allocations can now come from a ride or from a monthly shuttle cost run.
ALTER TABLE cost_allocation ALTER COLUMN ride_request_id DROP NOT NULL;
ALTER TABLE cost_allocation ADD COLUMN period VARCHAR(7);
ALTER TABLE cost_allocation DROP CONSTRAINT uq_cost_allocation_ride;
ALTER TABLE cost_allocation ADD CONSTRAINT uq_cost_allocation_ride UNIQUE (ride_request_id, cost_center_id, basis);
CREATE INDEX ix_cost_allocation_period ON cost_allocation (plant_id, period, basis);
